#!/bin/bash

### THESE ARE THE VARIABLES THAT MUST BE SET FOR EACH SYSTEM.
### IF THE SYSTEM WILL NOT USE IP ADDRS (SLURM) THE IP VARIABLES
### ARE UNNECESSARY. IF NNODES SHOULD NOT, OR MAY NOT BE THE DEFAULT
### IN UTIL (2), SET NNODES.
export IP_GRP=10.228.221
export PPN=4
export NCORES=16
export HOSTSIP="${IP_GRP}.141,${IP_GRP}.142"
export HOSTSNM="cots-006,cots-007"
